# Generated by Django 5.0.2 on 2024-05-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontSmart', '0005_rename_completed_task_iscompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completedTask',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
