# Generated by Django 5.0.2 on 2024-05-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontSmart', '0006_task_completedtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completedTask',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
