# Generated by Django 5.0.4 on 2024-05-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='role',
        ),
        migrations.AddField(
            model_name='userrole',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
